---
sudo: required
language: python
python: "2.7"

env:
  global:
    - ANSIBLE_CONFIG=tests/ansible.cfg
  matrix:
  - ANSIBLE_VERSION=latest
  #- ANSIBLE_VERSION=2.3.2.0
  - ANSIBLE_VERSION=2.2.2.0
  - ANSIBLE_VERSION=2.1.6.0

branches:
  only:
    - master

before_install:
  # update quietly
  - sudo apt-get update -qq

  # update SSL libraries to support SNI
  - sudo apt-get -y install python-urllib3 python-openssl python-pyasn1
  - sudo pip install ndg-httpsclient

  # install ruby & inspec
  - sudo apt-get -y install ruby ruby-dev make gcc
  - gem env
  - gem install inspec
  #- curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec


install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - pip install ansible-lint
  - ansible --version


script:
  # syntax check & linting
  - ansible-playbook -i tests/inventory --connection=local tests/test.yml --syntax-check
  - ansible-lint .

  # install role
  - ansible-playbook -i tests/inventory --connection=local tests/test.yml -vvvvv

  # test
  - echo "Waiting 10 seconds for netdata to start..." && sleep 10
  - echo "Running netdata InSpec tests"
  - inspec exec tests/default
