---
sudo: required
language: python
python: "2.7"

env:
  global:
    - ANSIBLE_CONFIG=tests/ansible.cfg
    - GEM_HOME=$HOME/.gems
  matrix:
  - ANSIBLE_VERSION=latest
  #- ANSIBLE_VERSION=2.3.2.0
  - ANSIBLE_VERSION=2.2.2.0
  - ANSIBLE_VERSION=2.1.6.0

branches:
  only:
    - master

before_install:
  # update quietly
  - sudo apt-get update -qq

  # update SSL libraries to support SNI
  - sudo apt-get -y install python-urllib3 python-openssl python-pyasn1
  - sudo pip install ndg-httpsclient

  # install ruby & inspec
  - sudo apt-get -y install ruby ruby-dev rubygems make gcc
  - gem env
  - sudo gem install inspec
  #- curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec


install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - pip install ansible-lint
  - ansible --version


script:
  # Ansible syntax check
  - ansible-playbook -i tests/inventory --connection=local tests/test.yml --syntax-check
  # Install role
  - ansible-playbook -i tests/inventory --connection=local tests/test.yml -vvvvv

  - ansible-lint .

  - inspec exec tests/default
