---
sudo: required
language: python
python:
  - "2.7"

env:
  global:
    - ANSIBLE_CONFIG=tests/ansible.cfg
  matrix:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.2.2.0

branches:
  only:
    - master

before_install:
  # update quietly
  - sudo apt-get update -qq

  # update SSL libraries
  - sudo apt-get install -y python-urllib3 python-openssl python-pyasn1
  - sudo pip install ndg-httpsclient


install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - pip install ansible-lint
  - ansible --version


script:
  # Ansible syntax check
  - ansible-playbook -i tests/inventory --connection=local tests/test.yml --syntax-check

  # Install role
  - ansible-playbook -i tests/inventory --connection=local tests/test.yml -vvvvv

  # lint
  - ansible-lint .
