---
- name: Download latest netdata
  include: netdata_latest.yml
  when: netdata_version == 'latest'

- name: Install netdata version {{ netdata_version }}
  include: netdata_version.yml
  when: netdata_version != 'latest'
